wallpaper {
  monitor = eDP-1
  path = /home/andy/walls/wall2.jpg
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-3
  path = /home/andy/walls/wall1.png
  fit_mode = cover
}

wallpaper {
  monitor =
  path = /home/andy/walls/wall2.jpg
  fit_mode = cover
}

splash = false
